services:
  app:
    build:
      context: .
      target: development
    ports:
      - "${PORT}:${PORT}"
    shm_size: '2gb'
    volumes:
      - .:/app
      - smartburgas_node_modules:/app/node_modules
    env_file:
      - .env

volumes:
  smartburgas_node_modules: